# Generated by Django 3.2.2 on 2022-01-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('bmi', models.IntegerField()),
                ('name', models.TextField(max_length=100)),
                ('fname', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(max_length=11)),
                ('veg_type', models.TextField()),
            ],
        ),
    ]
