# Generated by Django 3.2.2 on 2022-01-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
